#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { ApiClient } from "./client.js";

/**
 * The metaharness MCP server.
 *
 * This is the inbound half of being harness-agnostic: any MCP-speaking agent —
 * Claude Code, Codex, Cursor, Zed, Claude Desktop, a custom SDK loop — can author
 * a course through these six tools. The server itself holds no state; it proxies
 * to the local daemon, which owns the store and broadcasts changes to the UI, so
 * lessons appear on the learner's skill tree the moment they are written.
 *
 * Tool descriptions below are load-bearing. They are the only pedagogical brief
 * most agents will ever read, so they state the quality bar explicitly rather
 * than assuming the model will infer it.
 */

const API_BASE = process.env.METAHARNESS_API ?? "http://127.0.0.1:5273";
const TOKEN = process.env.METAHARNESS_TOKEN;
/** Set by the daemon when it spawns an authoring run, so tools need no course id. */
const DEFAULT_COURSE_ID = process.env.METAHARNESS_COURSE_ID;

const api = new ApiClient(API_BASE, TOKEN);

function ok(text: string) {
  return { content: [{ type: "text" as const, text }] };
}
function fail(text: string) {
  return { content: [{ type: "text" as const, text }], isError: true };
}

function courseIdOr(explicit: string | undefined): string {
  const id = explicit || DEFAULT_COURSE_ID;
  if (!id) {
    throw new Error(
      "No course id. Pass `courseId`, or run inside a metaharness build where METAHARNESS_COURSE_ID is set.",
    );
  }
  return id;
}

/** Wrap a handler so thrown errors come back as readable tool errors, not crashes. */
async function guard(fn: () => Promise<{ content: Array<{ type: "text"; text: string }>; isError?: boolean }>) {
  try {
    return await fn();
  } catch (err) {
    return fail((err as Error).message);
  }
}

const server = new McpServer(
  { name: "metaharness", version: "0.1.0" },
  {
    instructions:
      "Tools for authoring an interactive, Duolingo-style course. Typical flow: " +
      "course_get to see your assignment → source_add for each page → research_note to record verified claims → " +
      "course_plan to lay out units and lessons → lesson_write for each lesson → course_status when finished.",
  },
);

/* ------------------------------------------------------------------ */
/* Reading                                                             */
/* ------------------------------------------------------------------ */

server.registerTool(
  "course_get",
  {
    title: "Read the course",
    description:
      "Read the current course: its topic, level, unit/lesson structure, lesson ids, and which lessons are still unwritten. " +
      "Call this FIRST in any authoring run — lesson ids are generated by the system and you cannot write a lesson without one. " +
      "Set `includeContent` to also see already-written notes and exercises, which is useful for avoiding duplicate questions " +
      "across lessons; leave it off to keep the response small.",
    inputSchema: {
      courseId: z.string().optional().describe("Defaults to the course this run was started for"),
      includeContent: z.boolean().default(false).describe("Include notes and exercises of already-authored lessons"),
    },
  },
  async ({ courseId, includeContent }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const course = await api.get<any>(`/api/courses/${id}?content=${includeContent ? "1" : "0"}`);
      return ok(JSON.stringify(course, null, 2));
    }),
);

server.registerTool(
  "progress_get",
  {
    title: "Read learner progress",
    description:
      "Read the learner's progress on a course: XP, streak, which lessons are complete, per-concept mastery, and the weakest " +
      "concept tags. Use this when writing remedial or review lessons so practice targets what the learner actually keeps " +
      "getting wrong, rather than re-teaching what they have already mastered.",
    inputSchema: { courseId: z.string().optional() },
  },
  async ({ courseId }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const progress = await api.get<unknown>(`/api/courses/${id}/progress`);
      return ok(JSON.stringify(progress, null, 2));
    }),
);

/* ------------------------------------------------------------------ */
/* Planning                                                            */
/* ------------------------------------------------------------------ */

const planLesson = z.object({
  title: z.string().describe("Short and concrete, e.g. 'Why spikes form' — not 'Lesson 3'"),
  objective: z.string().describe("One sentence: what the learner can DO afterwards. Start with a verb."),
  kind: z
    .enum(["concept", "practice", "checkpoint"])
    .default("concept")
    .describe("concept = teaches something new; practice = drills earlier lessons; checkpoint = end-of-unit test"),
});

server.registerTool(
  "course_plan",
  {
    title: "Lay out the course structure",
    description:
      "Create the course's unit and lesson skeleton in one call. This replaces any existing structure, so call it once, " +
      "after your research and before writing any lessons.\n\n" +
      "Design rules:\n" +
      "- 3-6 units, each 3-6 lessons. A unit is a coherent theme; a lesson is ~3 minutes of work.\n" +
      "- Order by dependency: never rely on an idea the learner has not met yet. Lesson 1 must be approachable cold.\n" +
      "- Make every unit end with a `checkpoint` lesson, and include a `practice` lesson in longer units.\n" +
      "- Titles are learner-facing. Write them as promises of understanding, not as syllabus headings.\n\n" +
      "Returns the generated lesson ids, which you need for lesson_write.",
    inputSchema: {
      courseId: z.string().optional(),
      title: z.string().describe("Learner-facing course title"),
      description: z.string().default("").describe("Two sentences on what the course covers and who it is for"),
      level: z.enum(["beginner", "intermediate", "advanced"]).default("beginner"),
      color: z
        .string()
        .regex(/^#[0-9a-fA-F]{6}$/)
        .default("#769826")
        .describe(
          "Hex accent colour that themes the whole course. Pick one of the app's five: #769826 olive, #a1cb35 lime, #ffde4e sun yellow, #ff9d4d ember orange, #272622 ink.",
        ),
      units: z
        .array(
          z.object({
            title: z.string(),
            description: z.string().default(""),
            lessons: z.array(planLesson).min(1).max(8),
          }),
        )
        .min(1)
        .max(8),
      sources: z
        .array(z.object({ title: z.string(), url: z.string().optional(), note: z.string().optional() }))
        .default([])
        .describe("Sources your research drew on"),
    },
  },
  async ({ courseId, ...plan }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const result = await api.post<{ lessons: Array<{ id: string; unit: string; title: string }> }>(
        `/api/courses/${id}/plan`,
        plan,
      );
      return ok(
        `Course structure saved. Write each lesson with lesson_write using these ids:\n\n${result.lessons
          .map((l) => `${l.id}  ${l.unit} › ${l.title}`)
          .join("\n")}`,
      );
    }),
);

server.registerTool(
  "source_add",
  {
    title: "Archive a source page",
    description:
      "Fetch a page, keep a permanent copy of it on the course, and return its readable text.\n\n" +
      "Call this for every page you intend to cite, BEFORE research_note. The text returned is the copy the server will " +
      "check your quotes against, so quote from what this returns rather than from your own browsing — a page that serves " +
      "you something different from what it serves us will otherwise produce quotes that are honest and still rejected.\n\n" +
      "The archived copy is also what the learner sees when they click a cited sentence, so a page that fails here is one " +
      "nobody can check. Pick another source rather than citing it anyway.",
    inputSchema: {
      courseId: z.string().optional(),
      url: z.string().describe("The page to archive"),
      title: z.string().describe("Human-readable title, shown to the learner"),
      limit: z.number().int().min(1000).max(80000).default(40000).describe("Characters of text to return"),
    },
  },
  async ({ courseId, url, title, limit }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const res = await api.post<{ url: string; chars: number; truncated: boolean; text: string }>(
        `/api/courses/${id}/sources`,
        { url, title, limit },
      );
      return ok(
        `Archived ${res.url} (${res.chars} characters).` +
          (res.truncated ? ` Showing the first ${limit}.` : "") +
          `\n\n${res.text}`,
      );
    }),
);

server.registerTool(
  "research_note",
  {
    title: "Record research",
    description:
      "Record what you found as CLAIMS: each fact paired with the words in a source that support it.\n\n" +
      "Call source_add first for every page you intend to use — it archives the page and hands back its text. Quote from " +
      "THAT text, word for word. Every quote is checked against the archived copy before the call succeeds, and a claim " +
      "whose quote is not found is rejected with the closest passage it did find. Do not reconstruct a quote from memory; " +
      "copy it.\n\n" +
      "The claim ids returned here are what lesson_write requires to cite each paragraph, so gather the specific facts, " +
      "numbers, formulas and worked examples you will need later — not a summary of what you read.\n\n" +
      "`notes` is prose shown to the learner under 'About this course' and given back to you when authoring; it carries no " +
      "citations itself and is optional.",
    inputSchema: {
      courseId: z.string().optional(),
      notes: z.string().default("").describe("Markdown overview for the learner. Optional."),
      claims: z
        .array(
          z.object({
            text: z.string().describe("The fact, in your own words — this is what you will teach from"),
            sourceUrl: z.string().describe("URL of a page already passed to source_add"),
            quote: z
              .string()
              .describe("Word for word from that page's archived text. Checked; invented quotes are rejected."),
          }),
        )
        .default([]),
      sources: z
        .array(z.object({ title: z.string(), url: z.string().optional(), note: z.string().optional() }))
        .default([])
        .describe("Extra sources to archive. Prefer source_add, which returns the text you must quote from."),
      append: z.boolean().default(true).describe("Append to existing notes rather than replacing them"),
    },
  },
  async ({ courseId, notes, claims, sources, append }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const res = await api.post<{ claims: Array<{ id: string; text: string }> }>(
        `/api/courses/${id}/research`,
        { notes, claims, sources, append },
      );
      // The ids are the point of the reply: lesson_write cannot cite without them.
      return ok(
        `Verified ${claims.length} claim(s) against their sources.\n\n` +
          res.claims.map((c) => `${c.id}  ${c.text}`).join("\n"),
      );
    }),
);

/* ------------------------------------------------------------------ */
/* Authoring                                                           */
/* ------------------------------------------------------------------ */

const codeBlock = z.object({ language: z.string(), source: z.string() }).optional();
const commonFields = {
  prompt: z.string().describe("The question, as the learner reads it"),
  explanation: z.string().optional().describe("Shown after answering. Explain WHY, do not restate the answer."),
  hint: z.string().optional(),
  difficulty: z.number().int().min(1).max(3).default(2),
  tags: z.array(z.string()).default([]).describe("1-3 concept tags; these drive weak-area practice"),
  code: codeBlock,
};

const exerciseSchema = z.discriminatedUnion("type", [
  z.object({
    ...commonFields,
    type: z.literal("multiple_choice"),
    choices: z.array(z.string()).min(2).max(6),
    answer: z.string().describe("MUST be character-identical to one entry in choices"),
  }),
  z.object({
    ...commonFields,
    type: z.literal("multi_select"),
    choices: z.array(z.string()).min(3).max(8),
    answers: z.array(z.string()).min(1).describe("Each MUST appear verbatim in choices; leave at least one wrong"),
  }),
  z.object({ ...commonFields, type: z.literal("true_false"), answer: z.boolean() }),
  z.object({
    ...commonFields,
    type: z.literal("fill_blank"),
    prompt: z.string().describe("Use ___ (three underscores) for each blank"),
    blanks: z
      .array(z.object({ accepted: z.array(z.string()).min(1) }))
      .min(1)
      .max(4)
      .describe("One entry per ___, in order. List synonyms and spellings — the first is canonical."),
    wordBank: z.array(z.string()).max(10).optional().describe("Tap-to-fill tiles: every canonical answer plus distractors"),
  }),
  z.object({
    ...commonFields,
    type: z.literal("match_pairs"),
    pairs: z.array(z.object({ left: z.string(), right: z.string() })).min(3).max(6),
  }),
  z.object({
    ...commonFields,
    type: z.literal("order_sequence"),
    items: z.array(z.string()).min(3).max(7).describe("In the CORRECT order; the UI shuffles them for the learner"),
  }),
  z.object({
    ...commonFields,
    type: z.literal("categorize"),
    categories: z.array(z.string()).min(2).max(4),
    items: z.array(z.object({ text: z.string(), category: z.string() })).min(4).max(10),
  }),
  z.object({
    ...commonFields,
    type: z.literal("short_answer"),
    keyPoints: z.array(z.string()).min(1).max(5).describe("The ideas a correct answer must contain"),
    exemplar: z.string().describe("A model answer"),
    minWords: z.number().int().min(1).max(200).default(5),
  }),
  z.object({ ...commonFields, type: z.literal("flashcard"), back: z.string() }),
]);

server.registerTool(
  "lesson_write",
  {
    title: "Write one lesson",
    description:
      "Write the teaching notes and exercises for a single lesson. Call once per lesson id from course_plan/course_get.\n\n" +
      "BLOCKS (the teaching notes, 120-250 words total): one entry per paragraph, list, heading or equation, in reading " +
      "order. Lead with the intuition, then the precise statement, then a concrete example with real numbers. Inline math " +
      "as $x$ and display math as $$x$$; fenced code blocks are supported. Do not open with 'In this lesson we will…' — " +
      "just teach.\n\n" +
      "CITATIONS: every block of prose must list at least one claim id in `cites`, taken from what research_note returned. " +
      "Write from the claims you gathered; if a paragraph has no claim behind it, you are writing something you did not " +
      "verify — go and research it, or cut it. Headings, equations and short connectives do not need citations. The call " +
      "fails and names the offending blocks if any prose is uncited.\n\n" +
      "Cite the claim each paragraph actually rests on, not the nearest one. The server measures how much of each " +
      "paragraph's wording is accounted for by the claim it names, and the learner is shown that grade — a paragraph " +
      "labelled with a claim it only loosely relates to is displayed as unsupported, which is worse for you than " +
      "splitting it into two properly-cited paragraphs.\n\n" +
      "EXERCISES (4-8): every one must be answerable from the notes alone. Vary the type — a lesson that is eight multiple " +
      "choice questions in a row is a bad lesson. Order them easy → hard. Write distractors that represent real " +
      "misconceptions, not obvious throwaways; a learner who has not understood should be genuinely tempted. Give every " +
      "exercise an `explanation` that says why the right answer is right. Tag each with the concept it tests.\n\n" +
      "Answers are validated on write: if an answer is not among its choices, or a fill_blank's ___ count does not match its " +
      "blanks, the call fails with the specific problem and you should fix and retry.",
    inputSchema: {
      courseId: z.string().optional(),
      lessonId: z.string().describe("From course_plan or course_get"),
      blocks: z
        .array(
          z.object({
            markdown: z.string().describe("One paragraph, list, heading or equation"),
            cites: z
              .array(z.string())
              .default([])
              .describe("Claim ids from research_note that back this block. Required for prose."),
          }),
        )
        .min(1)
        .max(30)
        .describe("The lesson's notes, split into blocks so each can be traced to a source"),
      exercises: z.array(exerciseSchema).min(3).max(12),
    },
  },
  async ({ courseId, lessonId, blocks, exercises }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const result = await api.post<{ title: string; exerciseCount: number; remaining: number }>(
        `/api/courses/${id}/lessons/${lessonId}`,
        { blocks, exercises },
      );
      return ok(
        `Wrote “${result.title}” with ${result.exerciseCount} exercises. ${
          result.remaining > 0 ? `${result.remaining} lesson(s) still unwritten.` : "All lessons are now written."
        }`,
      );
    }),
);

server.registerTool(
  "course_status",
  {
    title: "Set course status",
    description:
      "Mark the course ready once every lesson is written, or failed if you cannot complete it. Setting 'ready' publishes it " +
      "to the learner's home screen. Only mark ready when course_get shows no unwritten lessons.",
    inputSchema: {
      courseId: z.string().optional(),
      status: z.enum(["authoring", "ready", "failed"]),
      error: z.string().optional().describe("Required when status is 'failed': what went wrong"),
    },
  },
  async ({ courseId, status, error }) =>
    guard(async () => {
      const id = courseIdOr(courseId);
      const result = await api.post<{ status: string; authored: number; total: number }>(`/api/courses/${id}/status`, {
        status,
        error,
      });
      return ok(`Course status is now "${result.status}" (${result.authored}/${result.total} lessons written).`);
    }),
);

const transport = new StdioServerTransport();
await server.connect(transport);
